# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='matricula',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='celular',
            field=models.CharField(max_length=50, verbose_name='Celular'),
        ),
    ]
