# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_disciplina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_auto_20170811_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome Completo')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('matricula', models.CharField(blank=True, max_length=13, null=True, verbose_name='Matrícula')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nome de Usuário')),
                ('coorientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coorientador', to='usuarios.Coordenador', verbose_name='Co-Orientador')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Disciplina', verbose_name='Disciplina')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='usuarios.Coordenador', verbose_name='Orientador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Atendentes',
                'verbose_name': 'Atendente',
                'ordering': ['nome'],
            },
        ),
    ]
