# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_atendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome Completo')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('cep', models.CharField(blank=True, max_length=30, verbose_name='CEP')),
                ('end', models.CharField(blank=True, max_length=50, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=30, verbose_name='Bairro')),
                ('referencia', models.CharField(blank=True, max_length=30, verbose_name='Ponto de Referência')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'verbose_name': 'Paciente',
                'ordering': ['nome', 'data_cadastro'],
            },
        ),
    ]
