# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180223_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(blank=True, max_length=30, verbose_name='Profissão'),
        ),
    ]
