# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='end',
            new_name='endereco',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=5, verbose_name='Número'),
        ),
    ]
