# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20170815_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(max_length=9, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
    ]
