# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20170815_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
