# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20180226_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaavaliacaomasculina',
            name='data',
            field=models.DateField(verbose_name='Data da Avaliação'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaomasculina',
            name='data_atendimento',
            field=models.DateField(verbose_name='Data do Atendimento'),
        ),
    ]
