# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20170815_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'ordering': ['paciente', 'data', 'hora', 'especialidade'], 'verbose_name': 'Prontuário', 'verbose_name_plural': 'Prontuários'},
        ),
        migrations.AddField(
            model_name='prontuario',
            name='especialidade',
            field=models.CharField(default='unk', max_length=50, verbose_name='Médico'),
            preserve_default=False,
        ),
    ]
