# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20180226_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='antecedentes_ciclo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Regularidade do Ciclo Menstrual'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='antecedentes_cirurgia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Cirurgia ou Doença Ginecológica Anterior'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='gestacional_fator_rh',
            field=models.CharField(choices=[('-', '-'), ('+', '+')], max_length=1, verbose_name='Fator RH'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='habitos_alimentacao',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Alimentação'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='habitos_drogas',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='habitos_etilismo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Etilismo'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='habitos_medicamentos',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='habitos_tabagismo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Tabagismo'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='historia_dor',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Existe Dor ao Urinar?'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='historia_perda',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Tem perda de urina?'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='infecciosas_hepatite',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Hepatite'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='infecciosas_rubeola',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Rubéola'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='infecciosas_sarampo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Sarampo'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='infecciosas_sifilis',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Sífilis'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='infecciosas_tuberculose',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Tuberculose'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='infecciosas_tuxoplasmose',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Tuxoplasmose'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='obstetrica_parto',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Cesárea', 'Cesárea'), ('Fórceps', 'Usou Fórceps')], max_length=40, verbose_name='Tipo de Parto'),
        ),
    ]
