# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20170815_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='especialidade',
            field=models.CharField(max_length=50, verbose_name='Especialidade'),
        ),
    ]
