# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20170815_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='beneficio',
            field=models.CharField(choices=[(None, '----'), (False, 'Não'), (True, 'Sim')], default=False, max_length=10, verbose_name='Possui beneficio do governo?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='colaborador',
            field=models.CharField(choices=[(None, '----'), (False, 'Não'), (True, 'Sim')], default=False, max_length=10, verbose_name='Colaborador da instituição?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(blank=True, max_length=14, verbose_name='Convênio Médico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_familiar',
            field=models.IntegerField(default=0, verbose_name='Mora com quantas pessoas?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='moradia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Condição da Moradia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(blank=True, max_length=14, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='referencia_nome',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='referencia_parentesco',
            field=models.CharField(blank=True, max_length=80, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='referencia_telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='renda',
            field=models.CharField(blank=True, max_length=14, verbose_name='Renda Mensal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='renda_total',
            field=models.CharField(blank=True, max_length=14, verbose_name='Renda Total da Família'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tratamento_sus',
            field=models.CharField(choices=[(None, '----'), (False, 'Não'), (True, 'Sim')], default=False, max_length=10, verbose_name='Realiza tratamento pelo SUS?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='valor_aluguel',
            field=models.CharField(blank=True, max_length=30, verbose_name='Se alugada, Valor'),
        ),
    ]
