# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20171027_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='beneficio',
            field=models.CharField(choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Possui beneficio do governo?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_familiar',
            field=models.CharField(blank=True, max_length=3, verbose_name='Mora com quantas pessoas?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tratamento_sus',
            field=models.CharField(choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Realiza tratamento pelo SUS?'),
        ),
    ]
