# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20180226_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_total',
            field=models.CharField(blank=True, max_length=80, verbose_name='Total de Pontos'),
        ),
    ]
