# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20180312_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaortopediaavaliacao',
            name='data',
            field=models.DateField(verbose_name='Data da Avaliação'),
        ),
    ]
