# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20180312_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Admissão'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='data_avaliacao',
            field=models.DateField(verbose_name='Data da Avaliação'),
        ),
    ]
