# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_fisioterapianeurologiainfantilavalicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_atitude',
            field=models.CharField(blank=True, choices=[('Passiva', 'Passiva'), ('Hipoativa', 'Hipoativa'), ('Ativa', 'Ativa')], max_length=10, verbose_name='Atitude'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_avd',
            field=models.CharField(blank=True, choices=[('Sem alteração', 'Sem alteração'), ('Deficiência', 'Deficiência')], max_length=10, verbose_name='AVD'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_cirurgia',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Interveções Cirúrgica?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_comunicacao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Comunicação'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_constipacao',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Constipação'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_convulsao',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Convulsões?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_dor',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Dor?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_escola',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Frequenta Escola?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_fisioterapia',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Realiza fisioterapia?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_refluxo',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Refluxo'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_sialorreia',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Sim', 'Não'), ('Não', 'Sim')], max_length=10, verbose_name='Sialorréia'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_visao',
            field=models.CharField(blank=True, choices=[('Sem alteração', 'Sem alteração'), ('Deficiência', 'Deficiência')], max_length=10, verbose_name='Visão'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='data',
            field=models.DateField(blank=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnóstico Clínico'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='exame_aquisicao_motora',
            field=models.TextField(blank=True, verbose_name='Aquisições Motoras'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='exame_diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnóstico Fisioterapêutico'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='exame_proposta',
            field=models.TextField(blank=True, verbose_name='Proposta Fisioterapêutico'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='historio_apgar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apgar'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='historio_comprimento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Comprimento'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='historio_pc',
            field=models.CharField(blank=True, max_length=50, verbose_name='P.C.'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='historio_peso',
            field=models.CharField(blank=True, max_length=50, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='idade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='medico',
            field=models.CharField(blank=True, max_length=50, verbose_name='Médico Responsável'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='responsavel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
    ]
