# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20171028_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
