# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20171028_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Nome'),
        ),
    ]
