# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_auto_20171028_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fisioterapianeurologiainfantilavalicao',
            old_name='nome',
            new_name='paciente',
        ),
    ]
