# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20171028_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_atitude',
            field=models.CharField(blank=True, choices=[('Passiva', 'Passiva'), ('Hipoativa', 'Hipoativa'), ('Ativa', 'Ativa')], max_length=20, verbose_name='Atitude'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_avd',
            field=models.CharField(blank=True, choices=[('Sem alteração', 'Sem alteração'), ('Deficiência', 'Deficiência')], max_length=20, verbose_name='AVD'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_cirurgia',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Interveções Cirúrgica?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_constipacao',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Constipação'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_convulsao',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Convulsões?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_dor',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Dor?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_escola',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Frequenta Escola?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_fisioterapia',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Realiza fisioterapia?'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_refluxo',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Refluxo'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_sialorreia',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Sialorréia'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologiainfantilavalicao',
            name='anamnese_visao',
            field=models.CharField(blank=True, choices=[('Sem alteração', 'Sem alteração'), ('Deficiência', 'Deficiência')], max_length=20, verbose_name='Visão'),
        ),
        migrations.AlterField(
            model_name='fisioterapiatriagem',
            name='atividade_fisica',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=10, verbose_name='Pratica atividade física?'),
        ),
        migrations.AlterField(
            model_name='fisioterapiatriagem',
            name='atividade_laboral',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=10, verbose_name='Pratica atividade laboral?'),
        ),
        migrations.AlterField(
            model_name='fisioterapiatriagem',
            name='uso_medicamentos',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=10, verbose_name='Faz uso de medicamentos?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='beneficio',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=10, verbose_name='Possui beneficio do governo?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='colaborador',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Colaborador da instituição?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tratamento_sus',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=10, verbose_name='Realiza tratamento pelo SUS?'),
        ),
    ]
