# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_auto_20171028_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioterapiaGeriatriaAvalicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(blank=True, max_length=50, verbose_name='Idade')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('data_admissao', models.DateField(blank=True, verbose_name='Data da Admissão')),
                ('data_avaliacao', models.DateField(blank=True, verbose_name='Data da Avaliação')),
                ('diagnostico_clinico', models.TextField(blank=True, verbose_name='Diagnóstico Clínico')),
                ('diagnostico_fisioterapeutico', models.TextField(blank=True, verbose_name='Diagnóstico Fisioterapêutico')),
                ('patologia', models.TextField(blank=True, verbose_name='Patologias/Problemas Associados')),
                ('medicamento', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=20, verbose_name='Faz uso de medicamentos?')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Quais medicamentos')),
                ('anamnese_queixa', models.TextField(blank=True, verbose_name='Queixa Principal/HMA')),
                ('anamnese_historia', models.TextField(blank=True, verbose_name='História Pregressa')),
                ('exame_pressao', models.CharField(blank=True, max_length=20, verbose_name='Pressão Arterial (mmHg)')),
                ('exame_freq_cardiaca', models.CharField(blank=True, max_length=20, verbose_name='Frequência Cardíaca (bpm)')),
                ('exame_freq_respiratoria', models.CharField(blank=True, max_length=20, verbose_name='Frequência Respiratória (irpm)')),
                ('exame_inspecao', models.CharField(blank=True, max_length=20, verbose_name='Inspeção')),
                ('exame_postura', models.CharField(blank=True, max_length=20, verbose_name='Postura')),
                ('exame_palpacao', models.CharField(blank=True, max_length=20, verbose_name='Palpação/Dor')),
                ('exame_trofismo', models.CharField(blank=True, max_length=20, verbose_name='Trofismo')),
                ('exame_tonus', models.CharField(blank=True, max_length=20, verbose_name='Tônus')),
                ('exame_sensibilidade', models.CharField(blank=True, max_length=20, verbose_name='Sensibilidade')),
                ('amplitude_superiores', models.CharField(blank=True, max_length=20, verbose_name='Membros Superiores')),
                ('amplitude_inferiores', models.CharField(blank=True, max_length=20, verbose_name='Membros Inferiores')),
                ('amplitude_tronco', models.CharField(blank=True, max_length=20, verbose_name='Tronco')),
                ('forca_superiores', models.CharField(blank=True, max_length=20, verbose_name='Membros Superiores')),
                ('forca_inferiores', models.CharField(blank=True, max_length=20, verbose_name='Membros Inferiores')),
                ('forca_tronco', models.CharField(blank=True, max_length=20, verbose_name='Tronco')),
                ('forca_retracao', models.CharField(blank=True, max_length=20, verbose_name='Retrações/Encurtamentos')),
                ('forca_equilibrio', models.CharField(blank=True, max_length=20, verbose_name='Equilíbrio')),
                ('forca_marcha', models.CharField(blank=True, max_length=20, verbose_name='Marcha')),
                ('forca_obs', models.TextField(blank=True, verbose_name='Obs.')),
                ('atividade_alimentacao', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Alimentação')),
                ('atividade_mobilidade', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15')], max_length=20, verbose_name='Mobilidade')),
                ('atividade_cuidado', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Cuidado Pessoal')),
                ('atividade_banheiro', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Uso do Banheiro')),
                ('atividade_banho', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Banho')),
                ('atividade_vestir', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Vestir-se')),
                ('atividade_transferencia', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15')], max_length=20, verbose_name='Tranferência')),
                ('atividade_escada', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Escada')),
                ('atividade_fecal', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Controle Fecal')),
                ('atividade_urinario', models.CharField(blank=True, choices=[('00', '00'), ('05', '05'), ('10', '10')], max_length=20, verbose_name='Controle Urinário')),
                ('atividade_total', models.CharField(blank=True, max_length=30, verbose_name='Total de Pontos')),
                ('planejamento_objetivos', models.TextField(blank=True, verbose_name='Objetivos')),
                ('planejamento_tratamento', models.TextField(blank=True, verbose_name='Tratamento')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Atendente', verbose_name='Estagiário')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Nome')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Coordenador', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Avaliação de Geriatria',
                'verbose_name_plural': 'Avaliações de Geriatria',
                'ordering': ['data_avaliacao'],
            },
        ),
    ]
