# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_auto_20171028_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_alimentacao',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Alimentação'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_banheiro',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Uso do Banheiro'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_banho',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Banho'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_cuidado',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Cuidado Pessoal'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_escada',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Escada'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_fecal',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Controle Fecal'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_mobilidade',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15')], default='00', max_length=20, verbose_name='Mobilidade'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_transferencia',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15')], default='00', max_length=20, verbose_name='Tranferência'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_urinario',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Controle Urinário'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='atividade_vestir',
            field=models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10')], default='00', max_length=20, verbose_name='Vestir-se'),
        ),
    ]
