# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_auto_20171028_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioterapiaBerg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data')),
                ('local', models.CharField(blank=True, max_length=20, verbose_name='Local')),
                ('Avaliador', models.CharField(blank=True, max_length=20, verbose_name='Avaliador')),
                ('berg_1', models.CharField(choices=[(4, '[4] - Capaz de levantar-se sem utilizar as mãos e estabilizar-se independentemente.'), (3, '[3] - Capaz de levantar-se independentemente utilizando as mãos.'), (2, '[2] - Capaz de levantar-se utilizando as mãos após diversas tentativas.'), (1, '[1] - Necessita de ajuda mínima para levantar-se ou estabilizar-se.'), (0, '[0] - Necessita de ajuda moderada ou máxima para levantar-se.')], default=0, max_length=120, verbose_name='Posição sentada para posição em pé: ')),
                ('berg_2', models.CharField(choices=[(4, '[4] - Capaz de permanecer em pé com segurança por 2 minutos.'), (3, '[3] - Capaz de permanecer em pé por 2 minutos com supervisão.'), (2, '[2] - Capaz de permanecer em pé por 30 segundos sem apoio.'), (1, '[1] - Necessita de várias tentativas para permanecer em pé por 30 segundos sem apoio.'), (0, '[0] - Incapaz de permanecer em pé por 30 segundos sem apoio.')], default=0, max_length=120, verbose_name='Permanecer em pé sem apoio: ')),
                ('berg_3', models.CharField(choices=[(4, '[4] - Capaz de permanecer sentado com segurança e com firmeza por 2 minutos.'), (3, '[3] - Capaz de permanecer sentado por 2 minutos sob supervisão.'), (2, '[2] - Capaz de oermanecer sentado por 30 segundos.'), (1, '[1] - Capaz de permanecer sentado por 10 segundos.'), (0, '[0] - Incapaz de permanecer sentado sem apoio durante 10 segundos.')], default=0, max_length=120, verbose_name='Permanecer sentado sem apoio nas costas, mas com os pés apoiados no chão ou num banquinho: ')),
                ('berg_4', models.CharField(choices=[(4, '[4] - Senta-se com segurança com uso mínimo das mãos'), (3, '[3] - Controla a descida utilizando as mãos.'), (2, '[2] - Utiliza a parte posterior das pernas contra a cadeira para controlar a descida.'), (1, '[1] - Senta-se independentemente, mas tem descida sem controle.'), (0, '[0] - Necessita de ajuda para sentar-se.')], default=0, max_length=120, verbose_name='Posição em pé para posição sentada: ')),
                ('berg_5', models.CharField(choices=[(4, '[4] - Capaz de transferir-se com segurança com uso mínimo das mãos.'), (3, '[3] - Caoaz de transferir-se com segurança com o uso das mãos.'), (2, '[2] - Capaz de transferir-se seguindo orentações verbais e/ou supervisão.'), (1, '[1] - Necessita de uma pessoa para ajudar.'), (0, '[0] - Necessita de duas pessoas para ajudar ou supervisionar para realizar a tarefa com segurança.')], default=0, max_length=120, verbose_name='Transferências: ')),
                ('berg_6', models.CharField(choices=[(4, '[4] - Capaz de permanecer em pé por 10 segundos com segurança.'), (3, '[3] - Capaz de permanecer em pé por 10 segundos com supervisão.'), (2, '[2] - Capaz de permanecer em pé por 3 segundos.'), (1, '[1] - Incapaz de permanecer com os olhos fechados durante 3 segundos, mas mantém-se em pé.'), (0, '[0] - Necessita de ajuda para não cair.')], default=0, max_length=120, verbose_name='Permanecer em pé sem apoio com os olhos fechados: ')),
                ('berg_7', models.CharField(choices=[(4, '[4] - Capaz de posicionar os pés juntos independentemente e permanecer por 1 minuto com segurança.'), (3, '[3] - Capaz de posicionar os pés juntos independentemente e permanecer por 1 minuto com supervisão.'), (2, '[2] - Capaz de posicionar os pés juntos independentemente e permanecer por 30 segundos.'), (1, '[1] - Necessita de ajuda para posicionar-se, mas é capaz de peranecer com os pés juntos durante 15 segundos.'), (0, '[0] - Necessita de ajuda para posicionar-se e é incapaz de permanecer nessa posição por 15 segundos.')], default=0, max_length=120, verbose_name='Permanecer em pé sem apoio com os pés juntos: ')),
                ('berg_8', models.CharField(choices=[(4, '[4] - Pode avançar à frente mais que 25 cm com segurança.'), (3, '[3] - Pode avançar à frente mais que 12,5 cm com segurança.'), (2, '[2] - Pode avançar à frente mais que 5 cm com segurança.'), (1, '[1] - Pode avançar à frente, mas necessita de supervisão.'), (0, '[0] - Perde o equilíbrio na tentativa, ou necessita de apoio externo.')], default=0, max_length=120, verbose_name='Alcançar a frente com o braço estendido permanecendo em pé: ')),
                ('berg_9', models.CharField(choices=[(4, '[4] - Capaz de pegar o chinelo com facilidade e segurança.'), (3, '[3] - Capaz de pegar o chinelo, mas necessita de supervisão.'), (2, '[2] - Incapaz de pegá-lo, mas se estica até ficar a 2-5 cm do chinelo e mantém o equilíbrio independentemente.'), (1, '[1] - Incapaz de pegá-lo, necessitando de supervisão enquanto está tentando.'), (0, '[0] - Incapaz de tentar, ou necessita de ajuda para não perder o equilíbrio ou cair.')], default=0, max_length=120, verbose_name='Pegar um objeto do chão a partir de uma posição em pé: ')),
                ('berg_10', models.CharField(choices=[(4, '[4] - Olha para trás de ambos os lados com uma boa distribuição do peso.'), (3, '[3] - Olha para trás somente de um lado, o lado contrário demonstra menor distribuição do peso.'), (2, '[2] - Vira somente para os lados, mas mantém o quilíbrio.'), (1, '[1] - Necessita de supervisão para virar.'), (0, '[0] - Necessita de ajuda para não perder o equilíbrio ou cair.')], default=0, max_length=120, verbose_name='Virar-se e olhar para trás por cima dos ombros direito e esquerdo enquanto permanece em pé: ')),
                ('berg_11', models.CharField(choices=[(4, '[4] - Capaz de girar 360 graus com segurança em 4 segundos ou menos.'), (3, '[3] - Capaz de girar 360 graus com segurança somente para um lado em 4 segundos ou menos.'), (2, '[2] - Capaz de girar 360 graus com segurança, mas lentamente.'), (1, '[1] - Necessita de supervisão próxima ou orientações verbais.'), (0, '[0] - Necessita de ajuda enquanto gira.')], default=0, max_length=120, verbose_name='Girar-se 360 graus: ')),
                ('berg_12', models.CharField(choices=[(4, '[4] - Capaz de permanecer em pé independentemente e com segurança, completando 8 movimentos em 20 segundos.'), (3, '[3] - Capaz de permanecer em pé independentemente e completar 8 movimentos em mais que 20 segundos.'), (2, '[2] - Capaz de completar 4 movimentos sem ajuda.'), (1, '[1] - Capaz de completar mais que 2 movimentos com o mínimo de ajuda.'), (0, '[0] - Incapaz de tentar, ou necessita de ajuda para não cair.')], default=0, max_length=120, verbose_name='Posicionar os pés alternadamente no degrau ou banquinho enquanto permanece em pé sem apoio: ')),
                ('berg_13', models.CharField(choices=[(4, '[4] - Capaz de colocar um pé imediatamente à frente do outro, independentemente, e permanecer por 30 segundos.'), (3, '[3] - Capaz de colocar um pé um pouco à frente do outro e levemente para o lado, independentemente, e permanecer por 30 segundos.'), (2, '[2] - Capaz de dar um pequeno passo independentemente, e permanecer por 30 segundos.'), (1, '[1] - Necessita de ajuda para dar o passo, porém permanece por 15 segundos.'), (0, '[0] - Perde o equilíbrio ao tentar dar um passo ou ficar de pé.')], default=0, max_length=120, verbose_name='Permanecer em pé sem apoio com um pé à frente: ')),
                ('berg_14', models.CharField(choices=[(4, '[4] - Capaz de levantar uma perna independentemente e permanecer por mais que 10 segundos.'), (3, '[3] - Capaz de levantar uma perna independentemente e permanecer por 5-10 segundos.'), (2, '[2] - Capaz de levantar uma perna independentemente e permanecer por mais que 3 segundos.'), (1, '[1] - Tenta levantar uma perna, mas é incapaz de permanecer por 3 segundos, embora permaneça em pé independentemente.'), (0, '[0] - Incapaz de tentar, ou necessita de ajuda para não cair.')], default=0, max_length=120, verbose_name='Permanecer em pé sobre uma perna: ')),
                ('berg_total', models.CharField(blank=True, max_length=20, verbose_name='Escore Total (Máximo = 56)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Escala de Equilíbrio Funcional de Berg',
                'ordering': ['data'],
                'verbose_name_plural': 'Escala de Equilíbrio Funcional de Berg',
            },
        ),
    ]
