# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_fisioterapiaberg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fisioterapiaberg',
            old_name='Avaliador',
            new_name='avaliador',
        ),
    ]
