# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_auto_20171029_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_1',
            field=models.CharField(default=0, max_length=10, verbose_name='1. Posição sentada para posição em pé: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_10',
            field=models.CharField(default=0, max_length=10, verbose_name='10. Virar-se e olhar para trás por cima dos ombros direito e esquerdo enquanto permanece em pé: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_11',
            field=models.CharField(default=0, max_length=10, verbose_name='11. Girar-se 360 graus: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_12',
            field=models.CharField(default=0, max_length=10, verbose_name='12. Posicionar os pés alternadamente no degrau ou banquinho enquanto permanece em pé sem apoio: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_13',
            field=models.CharField(default=0, max_length=10, verbose_name='13. Permanecer em pé sem apoio com um pé à frente: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_14',
            field=models.CharField(default=0, max_length=10, verbose_name='14. Permanecer em pé sobre uma perna: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_2',
            field=models.CharField(default=0, max_length=10, verbose_name='2. Permanecer em pé sem apoio: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_3',
            field=models.CharField(default=0, max_length=10, verbose_name='3. Permanecer sentado sem apoio nas costas, mas com os pés apoiados no chão ou num banquinho: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_4',
            field=models.CharField(default=0, max_length=10, verbose_name='4. Posição em pé para posição sentada: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_5',
            field=models.CharField(default=0, max_length=10, verbose_name='5. Transferências: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_6',
            field=models.CharField(default=0, max_length=10, verbose_name='6. Permanecer em pé sem apoio com os olhos fechados: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_7',
            field=models.CharField(default=0, max_length=10, verbose_name='7. Permanecer em pé sem apoio com os pés juntos: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_8',
            field=models.CharField(default=0, max_length=10, verbose_name='8. Alcançar a frente com o braço estendido permanecendo em pé: '),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='berg_9',
            field=models.CharField(default=0, max_length=10, verbose_name='9. Pegar um objeto do chão a partir de uma posição em pé: '),
        ),
    ]
