# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_fisioterapiageriatriaanamnese'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fisioterapiageriatriaanamnese',
            old_name='data_nascimentp',
            new_name='data_nascimento',
        ),
    ]
