# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_auto_20171030_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiageriatriaanamnese',
            name='membro_dominante',
            field=models.CharField(blank=True, choices=[('Direito', 'Direito'), ('Esquerdo', 'Esquerdo')], max_length=20, verbose_name='Membro Dominante'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaanamnese',
            name='ocupacao',
            field=models.CharField(blank=True, choices=[('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Autônomo', 'Autônomo'), ('Voluntário', 'Voluntário')], max_length=20, verbose_name='Ocupação Atual'),
        ),
    ]
