# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_auto_20171103_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='medicamento',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=20, verbose_name='Faz uso de medicamentos?'),
        ),
    ]
