# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_auto_20171103_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisioterapiageriatriaanamnese',
            options={'ordering': ['data'], 'verbose_name': 'Ficha de Avaliação / Anamnese', 'verbose_name_plural': 'Fichas de Avaliação / Anamnese'},
        ),
        migrations.RenameField(
            model_name='fisioterapiageriatriaanamnese',
            old_name='antecedentes_cirurgia_qual',
            new_name='atividade_fisica_qual',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='anamnese_queixa_principal',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='antecedentes_ciclo',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='antecedentes_cirurgia',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='antecedentes_idade_menarca',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='antecedentes_idade_sexual',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='gestacional_data',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='gestacional_dpp',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='gestacional_dum',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='gestacional_fator_rh',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='gestacional_idade',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='gestacional_tipo_sangue',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='nome_bebe',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='obstetrica_gestacao',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='obstetrica_parto',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='sexo_bebe',
        ),
        migrations.RemoveField(
            model_name='fisioterapiageriatriaanamnese',
            name='telefone',
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='alergia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Alergias?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='alergia_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='altura',
            field=models.CharField(blank=True, max_length=40, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='alzheimer',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Alzheimer?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='alzheimer_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='apneia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Apnéia?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='apneia_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='artrite',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Artrite/Artrose?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='artrite_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='artrite_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='asma',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Asma Brônquica?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='asma_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='atividade_fisica',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Pratica Atividade Física?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='atividade_fisica_frequencia',
            field=models.CharField(blank=True, max_length=40, verbose_name='Frequência?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='avc',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='AVC (Derrame Cerebral)?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='avc_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='aviso',
            field=models.CharField(blank=True, max_length=40, verbose_name='Em caso de Aviso Ligar p/'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='bronquiectasias',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Bronquiectasias?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='bronquiectasias_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='bronquite',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Bronquite Crônica?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='bronquite_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='bursite',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Bursite?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='bursite_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='bursite_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='carpo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Síndrome do Túnel do Carpo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='carpo_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='carpo_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='chagas',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Chagas?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='chagas_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='cirurgia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Realizou cirurgia nos últimos 5 anos?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='cirurgia_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='conduta',
            field=models.TextField(blank=True, verbose_name='Conduta'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='cuidar_casa',
            field=models.CharField(choices=[('Não', 'Não'), ('1 a 2 vezes', '1 a 2 vezes'), ('3 a 4 vezes', '3 a 4 vezes'), ('5 a 6 vezes', '5 a 6 vezes')], default='Não', max_length=10, verbose_name='Cuidar da Casa?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='depressao',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Depressão?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='depressao_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='diabetes',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Diabetes?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='diabetes_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='diabetes_tipo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnóstico Fisioterapêutico/Objetivos'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='emergencia',
            field=models.CharField(blank=True, max_length=40, verbose_name='Em caso de Emergência Ligar p/'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='enfisema',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Enfisema Pulmonar?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='enfisema_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fc',
            field=models.CharField(blank=True, max_length=40, verbose_name='FC'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fibromialgia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Fibromialgia?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fibromialgia_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fr',
            field=models.CharField(blank=True, max_length=40, verbose_name='FR'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fratura',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Fratura?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fratura_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fratura_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fumante',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Fumante?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fumante_qnd_parou',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quando Parou?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='fumante_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Há Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hernia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Hérnia de Disco?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hernia_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipertensao',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Hipertensão?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipertensao_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipertiroidismo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Hipertiroidismo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipertiroidismo_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipertiroidismo_tipo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipotensao',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Hipotensão?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipotensao_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipotiroidismo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Hipotiroidismo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipotiroidismo_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='hipotiroidismo_tipo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='imc',
            field=models.CharField(blank=True, max_length=40, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='incontinencia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Incontinênia Urinária?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='incontinencia_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='infarto',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Infarto Agudo do Miocárdio?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='infarto_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='jardinagem',
            field=models.CharField(choices=[('Não', 'Não'), ('1 a 2 vezes', '1 a 2 vezes'), ('3 a 4 vezes', '3 a 4 vezes'), ('5 a 6 vezes', '5 a 6 vezes')], default='Não', max_length=10, verbose_name='Jardinagem?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='labirintite',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Labirintite?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='labirintite_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='lavar_roupa',
            field=models.CharField(choices=[('Não', 'Não'), ('1 a 2 vezes', '1 a 2 vezes'), ('3 a 4 vezes', '3 a 4 vezes'), ('5 a 6 vezes', '5 a 6 vezes')], default='Não', max_length=10, verbose_name='Lavar Roupa?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='lombalgia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Lombalgia?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='lombalgia_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='lombalgia_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='medicamento',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=20, verbose_name='Faz uso de medicamentos?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='medicamentos',
            field=models.TextField(blank=True, verbose_name='Quais medicamentos?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='membro_dominante',
            field=models.CharField(blank=True, choices=[('Direito', 'Direito'), ('Esquerdo', 'Esquerdo')], max_length=20, verbose_name='Membro Dominante'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='obesidade',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Obesidade?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='obesidade_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='obesidade_tipo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='ocupacao',
            field=models.CharField(blank=True, choices=[('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Autônomo', 'Autônomo'), ('Voluntário', 'Voluntário')], max_length=20, verbose_name='Ocupação Atual'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='osteoporose',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Osteoporose?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='osteoporose_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='osteoporose_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_cardiovasculares',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Outras?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_cardiovasculares_quais',
            field=models.TextField(blank=True, verbose_name='Quais?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_metabolicas',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Outras?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_metabolicas_quais',
            field=models.TextField(blank=True, verbose_name='Quais?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_neurologicas',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Outras?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_neurologicas_quais',
            field=models.TextField(blank=True, verbose_name='Quais?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_osteomioarticulares',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Outras?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_osteomioarticulares_quais',
            field=models.TextField(blank=True, verbose_name='Quais?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_psicossomaticas',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Outras?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_psicossomaticas_quais',
            field=models.TextField(blank=True, verbose_name='Quais?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_respiratorias',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Outras?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='outras_respiratorias_quais',
            field=models.TextField(blank=True, verbose_name='Quais?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='pa',
            field=models.CharField(blank=True, max_length=40, verbose_name='PA'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='passar_roupa',
            field=models.CharField(choices=[('Não', 'Não'), ('1 a 2 vezes', '1 a 2 vezes'), ('3 a 4 vezes', '3 a 4 vezes'), ('5 a 6 vezes', '5 a 6 vezes')], default='Não', max_length=10, verbose_name='Passar Roupa?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='peso',
            field=models.CharField(blank=True, max_length=40, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Sofreu quedas no último ano?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_2_anos',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Nos 2 últimos anos o Sr(a) teve alguma queda?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_aonde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Aonde foi?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_cirurgia',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Fez cirurgia?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_cirurgia_qual',
            field=models.CharField(blank=True, max_length=40, verbose_name='Qual?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_como',
            field=models.CharField(blank=True, max_length=40, verbose_name='Como foi?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_hospital',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Precisou ser hospitalizado?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_hospital_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_protese',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Prótese?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='queda_protese_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='saturacao',
            field=models.CharField(blank=True, max_length=40, verbose_name='Saturação'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='stress',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Stress?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='stress_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='supermecado',
            field=models.CharField(choices=[('Não', 'Não'), ('1 a 2 vezes', '1 a 2 vezes'), ('3 a 4 vezes', '3 a 4 vezes'), ('5 a 6 vezes', '5 a 6 vezes')], default='Não', max_length=10, verbose_name='Ir ao supermecado?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='tempo_trabalho',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tempo de Trabalho'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='tendinite',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Tendinite?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='tendinite_onde',
            field=models.CharField(blank=True, max_length=40, verbose_name='Onde?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='tendinite_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='trabalha',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Trabalha?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='traumatismo',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Traumatismo Cranioencefálico?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='traumatismo_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='vaso_vagal',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Síndrome do Vaso Vagal?'),
        ),
        migrations.AddField(
            model_name='fisioterapiageriatriaanamnese',
            name='vaso_vagal_tempo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Quanto Tempo?'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaanamnese',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaanamnese',
            name='idade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Idade'),
        ),
    ]
