# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_auto_20171103_0918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atendente',
            new_name='Aluno',
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
