# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_auto_20171104_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='coorientador',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='orientador',
        ),
        migrations.AddField(
            model_name='aluno',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Supervisor', verbose_name='Supervisor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='celular',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
