# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_fisioterapiaavaliacaomaculina'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioterapiaavaliacaomaculina',
            name='antecedentes_carregamento_peso',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Carregamento de Peso'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaomaculina',
            name='antecedentes_peso',
            field=models.CharField(blank=True, max_length=40, verbose_name='Peso'),
        ),
    ]
