# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0046_fisioterapiaavaliacaofeminina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FisioterapiaAvaliacaoMaculina',
            new_name='FisioterapiaAvaliacaoMasculina',
        ),
    ]
