# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0047_auto_20171118_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioterapiaavaliacaofeminina',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo da Consulta'),
        ),
    ]
