# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0048_fisioterapiaavaliacaofeminina_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaavaliacaofeminina',
            name='exame_altura',
            field=models.CharField(blank=True, max_length=40, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaofeminina',
            name='exame_imc',
            field=models.CharField(blank=True, max_length=40, verbose_name='IMC (Kg/m²)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaofeminina',
            name='exame_peso',
            field=models.CharField(blank=True, max_length=40, verbose_name='Peso (Kg)'),
        ),
    ]
