# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0050_fisioterapiaacidentevascularencefalico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioterapiaEscleroseMultipla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data da Avaliação')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('idade', models.CharField(blank=True, max_length=40, verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.CharField(blank=True, max_length=40, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=40, verbose_name='Profissão')),
                ('estado_civil', models.CharField(blank=True, max_length=40, verbose_name='Estado Civil')),
                ('diagnostico_clinico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Clínico')),
                ('diagnostico_fisioterapico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Fisioterápico')),
                ('dados_pa', models.CharField(blank=True, max_length=40, verbose_name='P.A.')),
                ('dados_fc', models.CharField(blank=True, max_length=40, verbose_name='F.C.')),
                ('dados_fr', models.CharField(blank=True, max_length=40, verbose_name='F.R.')),
                ('dados_t', models.CharField(blank=True, max_length=40, verbose_name='T°')),
                ('info_medicamentos', models.TextField(blank=True, verbose_name='Medicamentos Utilizados')),
                ('info_exames', models.TextField(blank=True, verbose_name='Exames Complementares')),
                ('info_antecedentes', models.TextField(blank=True, verbose_name='Antecedentes Cirúrgicos')),
                ('info_adm', models.TextField(blank=True, verbose_name='ADM')),
                ('anamnese_qp', models.TextField(blank=True, verbose_name='Q.P.')),
                ('anamnese_hmpa', models.TextField(blank=True, verbose_name='H.M.P.A.')),
                ('exame_tonus', models.CharField(blank=True, choices=[('Grau 1', 'Grau 1: Tônus normal.'), ('Grau 2', 'Grau 2: Aumento leve do tônus - movimentação passiva com certa resistência.'), ('Grau 3', 'Grau 3: Aumento moderado do tônus - maior resistência à movimentação passiva.'), ('Grau 4', 'Grau 4: Aumento considerável do tônus - movimentação passiva é difícil.'), ('Grau 5', 'Grau 5: Rigidez em flexão ou extensão.')], max_length=40, verbose_name='Escala de Avaliação do Tônus Asworth')),
                ('exame_trofismo', models.CharField(blank=True, choices=[('Normo', 'Normo'), ('Hipertrofia', 'Hipertrofia'), ('Hipotrofia', 'Hipotrofia')], max_length=40, verbose_name='Trofismo')),
                ('reflexos_bicipital', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Bicipital')),
                ('reflexos_tricipital', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Tricipital')),
                ('reflexos_patelar', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Patelar')),
                ('reflexos_anquileu', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Anquileu')),
                ('ms_direito_ombro', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Ombro')),
                ('ms_direito_cotovelo', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Cotovelo')),
                ('ms_direito_punho', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Punho')),
                ('ms_direito_mao', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Mão')),
                ('ms_direito_dedos', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Dedos')),
                ('ms_esquerdo_ombro', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Ombro')),
                ('ms_esquerdo_cotovelo', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Cotovelo')),
                ('ms_esquerdo_punho', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Punho')),
                ('ms_esquerdo_mao', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Mão')),
                ('ms_esquerdo_dedos', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Dedos')),
                ('mi_direito_quadril', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Quadril')),
                ('mi_direito_joelho', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Joelho')),
                ('mi_direito_tornozelo', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Tornozelo')),
                ('mi_direito_pe', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Pé')),
                ('mi_esquerdo_quadril', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Quadril')),
                ('mi_esquerdo_joelho', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Joelho')),
                ('mi_esquerdo_tornozelo', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Tornozelo')),
                ('mi_esquerdo_pe', models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Reduzida')], max_length=40, verbose_name='Pé')),
                ('desenvolvimento_avds', models.CharField(blank=True, choices=[('Independente', 'Independente'), ('Dependente', 'Dependente'), ('Semi-Independente', 'Semi-Independente')], max_length=40, verbose_name="AVD's")),
                ('desenvolvimento_neurofuncional', models.TextField(blank=True, verbose_name='NeuroFuncional')),
                ('desenvolvimento_conduta', models.TextField(blank=True, verbose_name='Conduta Fisioterapêutica')),
                ('kurtzke_piramidais', models.CharField(blank=True, choices=[('0', 'Normal'), ('1', 'Sinais anormais sem incapacidades'), ('2', 'Incapacidade mínima'), ('3', 'Paraparesia ou Hemiparesia leve ou moderada, Monoparesia grave'), ('4', 'Paraparesia ou Hemiparesia acentuada, Quadriparesia moderada; ou Monoplegia'), ('5', 'Paraplegia, Hemiplegia ou Quadriparesia acentuada'), ('6', 'Quadriplegia')], max_length=40, verbose_name='Funções Piramidais')),
                ('kurtzke_cerebelares', models.TextField(blank=True, verbose_name='Funções Cerebelares')),
                ('atendimento_estagiario', models.CharField(blank=True, max_length=40, verbose_name='Estagiário (a)')),
                ('atendimento_supervisor', models.CharField(blank=True, max_length=40, verbose_name='Supervissor (a)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Avaliações Esclerose Múltipla',
                'ordering': ['data'],
                'verbose_name': 'Avaliação Esclerose Múltipla',
            },
        ),
    ]
