# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0051_fisioterapiaesclerosemultipla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_direito_joelho',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_direito_pe',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_direito_quadril',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_direito_tornozelo',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_esquerdo_joelho',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_esquerdo_pe',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_esquerdo_quadril',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='mi_esquerdo_tornozelo',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_direito_cotovelo',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_direito_dedos',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_direito_mao',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_direito_ombro',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_direito_punho',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_esquerdo_cotovelo',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_esquerdo_dedos',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_esquerdo_mao',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_esquerdo_ombro',
        ),
        migrations.RemoveField(
            model_name='fisioterapiaesclerosemultipla',
            name='ms_esquerdo_punho',
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmii',
            field=models.CharField(blank=True, max_length=40, verbose_name='MMII'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmii_direito_14',
            field=models.CharField(blank=True, max_length=40, verbose_name='Direito - 14cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmii_direito_21',
            field=models.CharField(blank=True, max_length=40, verbose_name='Direito - 21cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmii_direito_7',
            field=models.CharField(blank=True, max_length=40, verbose_name='Direito - 7cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmii_esquerdo_14',
            field=models.CharField(blank=True, max_length=40, verbose_name='Esquerdo - 14cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmii_esquerdo_21',
            field=models.CharField(blank=True, max_length=40, verbose_name='Esquerdo - 21cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmii_esquerdo_7',
            field=models.CharField(blank=True, max_length=40, verbose_name='Esquerdo - 7cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmss',
            field=models.CharField(blank=True, max_length=40, verbose_name='MMSS'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmss_direito_14',
            field=models.CharField(blank=True, max_length=40, verbose_name='Direito - 14cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmss_direito_21',
            field=models.CharField(blank=True, max_length=40, verbose_name='Direito - 21cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmss_direito_7',
            field=models.CharField(blank=True, max_length=40, verbose_name='Direito - 7cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmss_esquerdo_14',
            field=models.CharField(blank=True, max_length=40, verbose_name='Esquerdo - 14cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmss_esquerdo_21',
            field=models.CharField(blank=True, max_length=40, verbose_name='Esquerdo - 21cm'),
        ),
        migrations.AddField(
            model_name='fisioterapiaesclerosemultipla',
            name='mmss_esquerdo_7',
            field=models.CharField(blank=True, max_length=40, verbose_name='Esquerdo - 7cm'),
        ),
    ]
