# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0053_fisioterapiatrm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioterapiaNeurologica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data da Avaliação')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('idade', models.CharField(blank=True, max_length=40, verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.CharField(blank=True, max_length=40, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=40, verbose_name='Profissão')),
                ('estado_civil', models.CharField(blank=True, max_length=40, verbose_name='Estado Civil')),
                ('diagnostico_clinico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Clínico')),
                ('diagnostico_fisioterapico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Fisioterápico')),
                ('dados_pa', models.CharField(blank=True, max_length=40, verbose_name='P.A.')),
                ('dados_fc', models.CharField(blank=True, max_length=40, verbose_name='F.C.')),
                ('dados_fr', models.CharField(blank=True, max_length=40, verbose_name='F.R.')),
                ('dados_t', models.CharField(blank=True, max_length=40, verbose_name='T°')),
                ('info_medicamentos', models.TextField(blank=True, verbose_name='Medicamentos Utilizados')),
                ('info_patologias', models.TextField(blank=True, verbose_name='Patologias Associadas')),
                ('info_antecedentes', models.TextField(blank=True, verbose_name='Antecedentes Cirúrgicos')),
                ('info_sensibilidade', models.TextField(blank=True, verbose_name='Sensibilidade')),
                ('anamnese_qp', models.TextField(blank=True, verbose_name='Q.P.')),
                ('anamnese_hmpa', models.TextField(blank=True, verbose_name='H.M.A.')),
                ('anamnese_hp', models.TextField(blank=True, verbose_name='H.P.')),
                ('exame_deformidades', models.TextField(blank=True, verbose_name='Deformidades')),
                ('exame_tonus', models.TextField(blank=True, verbose_name='Tônus')),
                ('exame_trofismo', models.TextField(blank=True, verbose_name='Trofismo')),
                ('exame_retracoes_encurtamento', models.TextField(blank=True, verbose_name='Retrações ou Encurtamentos')),
                ('reflexos_bicipital', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Bicipital - C6')),
                ('reflexos_tricipital', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Tricipital - C7')),
                ('reflexos_patelar', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Patelar - L2, L3 e L4')),
                ('reflexos_anquileu', models.CharField(blank=True, choices=[('Normoreflexia', 'Normoreflexia'), ('Hiporeflexia', 'Hiporeflexia'), ('Hiperreflexia', 'Hiperreflexia'), ('Arreflexia', 'Arreflexia')], max_length=40, verbose_name='Anquileu - L5, S1 e S2')),
                ('adm_ms', models.TextField(blank=True, verbose_name='Membros Superiores')),
                ('adm_mi', models.TextField(blank=True, verbose_name='Membros Inferiores')),
                ('adm_avd', models.CharField(blank=True, choices=[('Independente', 'Independente'), ('Dependente', 'Dependente'), ('Semi-Independente', 'Semi-Independente')], max_length=40, verbose_name="AVD's")),
                ('adm_marcha', models.CharField(blank=True, max_length=40, verbose_name='Marcha')),
                ('desenvolvimento_conduta', models.TextField(blank=True, verbose_name='Conduta Fisioterapêutica')),
                ('desenvolvimento_objetivo', models.TextField(blank=True, verbose_name='Objetivos de Tratamento')),
                ('atendimento_estagiario', models.CharField(blank=True, max_length=40, verbose_name='Estagiário (a)')),
                ('atendimento_supervisor', models.CharField(blank=True, max_length=40, verbose_name='Supervissor (a)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Avaliação Neurológica',
                'verbose_name_plural': 'Avaliações Neurológica',
                'ordering': ['data'],
            },
        ),
    ]
