# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0054_fisioterapianeurologica'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioterapiaParkinson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data da Avaliação')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('idade', models.CharField(blank=True, max_length=40, verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.CharField(blank=True, max_length=40, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=40, verbose_name='Profissão')),
                ('estado_civil', models.CharField(blank=True, max_length=40, verbose_name='Estado Civil')),
                ('diagnostico_clinico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Clínico')),
                ('diagnostico_fisioterapico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Fisioterápico')),
                ('dados_pa', models.CharField(blank=True, max_length=40, verbose_name='P.A.')),
                ('dados_fc', models.CharField(blank=True, max_length=40, verbose_name='F.C.')),
                ('dados_fr', models.CharField(blank=True, max_length=40, verbose_name='F.R.')),
                ('dados_t', models.CharField(blank=True, max_length=40, verbose_name='T°')),
                ('info_medicamentos', models.TextField(blank=True, verbose_name='Medicamentos Utilizados')),
                ('info_patologias', models.TextField(blank=True, verbose_name='Patologias Associadas')),
                ('info_antecedentes', models.TextField(blank=True, verbose_name='Antecedentes Cirúrgicos')),
                ('anamnese_qp', models.TextField(blank=True, verbose_name='Q.P.')),
                ('anamnese_hmpa', models.TextField(blank=True, verbose_name='H.M.P.A.')),
                ('exame_1', models.CharField(default=0, max_length=10, verbose_name='Bradicinesia de Mãos - Incluindo Escrita Manual: ')),
                ('exame_2', models.CharField(default=0, max_length=10, verbose_name='Rigidez: ')),
                ('exame_3', models.CharField(default=0, max_length=10, verbose_name='Postura: ')),
                ('exame_4', models.CharField(default=0, max_length=10, verbose_name='Balanceio de Membros Superior: ')),
                ('exame_5', models.CharField(default=0, max_length=10, verbose_name='Marcha: ')),
                ('exame_6', models.CharField(default=0, max_length=10, verbose_name='Tremor: ')),
                ('exame_7', models.CharField(default=0, max_length=10, verbose_name='Face: ')),
                ('exame_8', models.CharField(default=0, max_length=10, verbose_name='Seborréia: ')),
                ('exame_9', models.CharField(default=0, max_length=10, verbose_name='Fala: ')),
                ('exame_10', models.CharField(default=0, max_length=10, verbose_name='Cuidados Pessoais: ')),
                ('exame_total', models.CharField(blank=True, max_length=20, verbose_name='Total')),
                ('exame_adm', models.TextField(blank=True, verbose_name='ADM')),
                ('exame_trofismo', models.TextField(blank=True, verbose_name='Trofismo')),
                ('desenvolvimento_objetivo', models.TextField(blank=True, verbose_name='Objetivos de Tratamento')),
                ('desenvolvimento_conduta', models.TextField(blank=True, verbose_name='Conduta Fisioterapêutica')),
                ('desenvolvimento_complemento', models.TextField(blank=True, verbose_name='Complementações')),
                ('atendimento_estagiario', models.CharField(blank=True, max_length=40, verbose_name='Estagiário (a)')),
                ('atendimento_supervisor', models.CharField(blank=True, max_length=40, verbose_name='Supervissor (a)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Avaliações Parkinson',
                'verbose_name': 'Avaliação Parkinson',
                'ordering': ['data'],
            },
        ),
    ]
