# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0055_fisioterapiaparkinson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaparkinson',
            name='exame_total',
            field=models.CharField(blank=True, max_length=40, verbose_name='Total'),
        ),
    ]
