# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0056_auto_20171127_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioterapiaParalisiaFacial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data da Avaliação')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('idade', models.CharField(blank=True, max_length=40, verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.CharField(blank=True, max_length=40, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=40, verbose_name='Profissão')),
                ('estado_civil', models.CharField(blank=True, max_length=40, verbose_name='Estado Civil')),
                ('diagnostico_clinico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Clínico')),
                ('diagnostico_fisioterapico', models.CharField(blank=True, max_length=40, verbose_name='Diagnóstico Fisioterápico')),
                ('dados_pa', models.CharField(blank=True, max_length=40, verbose_name='P.A.')),
                ('dados_fc', models.CharField(blank=True, max_length=40, verbose_name='F.C.')),
                ('dados_fr', models.CharField(blank=True, max_length=40, verbose_name='F.R.')),
                ('dados_t', models.CharField(blank=True, max_length=40, verbose_name='T°')),
                ('info_medicamentos', models.TextField(blank=True, verbose_name='Medicamentos Utilizados')),
                ('info_patologias', models.TextField(blank=True, verbose_name='Patologias Associadas')),
                ('info_antecedentes', models.TextField(blank=True, verbose_name='Antecedentes Cirúrgicos')),
                ('anamnese_qp', models.TextField(blank=True, verbose_name='Q.P.')),
                ('anamnese_hmpa', models.TextField(blank=True, verbose_name='H.M.P.A.')),
                ('exame_desvio_facial', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Desvio Facial')),
                ('exame_desvio_septo', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Desvio do Septo Nasal')),
                ('exame_sulco_face', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sulcos da Face')),
                ('exame_conjuntivite', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Conjuntivite')),
                ('exame_lagoftalmo', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Lagoftalmo')),
                ('exame_sinal_bell', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sinal Bell')),
                ('exame_sinal_negro', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sinal Negro')),
                ('exame_reflexo_ciliar', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Retardado', 'Retardado')], max_length=40, verbose_name='Reflexo Ciliar')),
                ('exame_linguagem', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Alterações da Linguagem (P-B-M)')),
                ('exame_auditiva', models.CharField(choices=[('Hipoacusia', 'Hipoacusia'), ('Hiperacusia', 'Hiperacusia'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Alteração Auditiva')),
                ('exame_gustativa', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Alteração Gustativa')),
                ('exame_tonus', models.CharField(choices=[('Hipertônico', 'Hipertônico'), ('Hipotônico', 'Hipotônico'), ('Normal', 'Normal')], max_length=40, verbose_name='Tônus Muscular')),
                ('exame_dor', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Dor Retroauricular')),
                ('exame_sincinesias', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sincinésias')),
                ('exame_lingua', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Motricidade da Língua')),
                ('exame_paralisia', models.CharField(choices=[('Central', 'Central'), ('Periférica', 'Periférica')], max_length=40, verbose_name='Paralisia Facial Difinitiva')),
                ('desenvolvimento_conclusao', models.TextField(blank=True, verbose_name='Conclusão da Prova de Função')),
                ('desenvolvimento_objetivo', models.TextField(blank=True, verbose_name='Objetivos do Tratamento')),
                ('desenvolvimento_conduta', models.TextField(blank=True, verbose_name='Conduta Fisioterápica')),
                ('atendimento_estagiario', models.CharField(blank=True, max_length=40, verbose_name='Estagiário (a)')),
                ('atendimento_supervisor', models.CharField(blank=True, max_length=40, verbose_name='Supervissor (a)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Nome')),
            ],
            options={
                'ordering': ['data'],
                'verbose_name_plural': 'Avaliações Paralisia Facial',
                'verbose_name': 'Avaliação Paralisia Facial',
            },
        ),
    ]
