# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0057_fisioterapiaparalisiafacial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_alar_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Alar Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_alar_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Alar Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_alar_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Alar Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_alar_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Alar Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_alar_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Alar Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_alar_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Alar Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bico_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Fazer Bico Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bico_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fazer Bico Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bico_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fazer Bico Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bico_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fazer Bico Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bico_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Fazer Bico Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bico_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fazer Bico Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bucinador_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Bucinador Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bucinador_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Bucinador Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bucinador_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Bucinador Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bucinador_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Bucinador Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bucinador_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Bucinador Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_bucinador_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Bucinador Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canino_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Canino Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canino_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Canino Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canino_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Canino Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canino_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Canino Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canino_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Canino Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canino_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Canino Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canto_boca_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Levar o Canto da Boca P/ Baixo Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canto_boca_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Levar o Canto da Boca P/ Baixo Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canto_boca_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Levar o Canto da Boca P/ Baixo Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canto_boca_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Levar o Canto da Boca P/ Baixo Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canto_boca_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Levar o Canto da Boca P/ Baixo Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_canto_boca_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Levar o Canto da Boca P/ Baixo Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comissura_labial_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevar a Comissura Labial por Trás Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comissura_labial_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar a Comissura Labial por Trás Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comissura_labial_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar a Comissura Labial por Trás Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comissura_labial_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar a Comissura Labial por Trás Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comissura_labial_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevar a Comissura Labial por Trás Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comissura_labial_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar a Comissura Labial por Trás Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comprimir_narinas_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Comprimir as Narinas Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comprimir_narinas_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Comprimir as Narinas Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comprimir_narinas_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Comprimir as Narinas Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comprimir_narinas_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Comprimir as Narinas Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comprimir_narinas_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Comprimir as Narinas Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_comprimir_narinas_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Comprimir as Narinas Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depresor_labio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Depressor do Lábio Inferior Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depresor_labio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Lábio Inferior Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depresor_labio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Lábio Inferior Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depresor_labio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Lábio Inferior Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depresor_labio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Depressor do Lábio Inferior Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depresor_labio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Lábio Inferior Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depressor_septo_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Depressor do Septo Nasal Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depressor_septo_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Septo Nasal Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depressor_septo_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Septo Nasal Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depressor_septo_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Septo Nasal Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depressor_septo_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Depressor do Septo Nasal Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_depressor_septo_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Depressor do Septo Nasal Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_labio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Deprimir Lábio Inferior, Ângulo da Boca P/ Baixo Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_labio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir Lábio Inferior, Ângulo da Boca P/ Baixo Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_labio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir Lábio Inferior, Ângulo da Boca P/ Baixo Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_labio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir Lábio Inferior, Ângulo da Boca P/ Baixo Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_labio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Deprimir Lábio Inferior, Ângulo da Boca P/ Baixo Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_labio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir Lábio Inferior, Ângulo da Boca P/ Baixo Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_septo_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Deprimir o Septo Nasal Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_septo_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir o Septo Nasal Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_septo_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir o Septo Nasal Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_septo_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir o Septo Nasal Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_septo_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Deprimir o Septo Nasal Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_deprimir_septo_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Deprimir o Septo Nasal Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_dilatar_narinas_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Dilatar as Narinas Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_dilatar_narinas_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Dilatar as Narinas Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_dilatar_narinas_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Dilatar as Narinas Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_dilatar_narinas_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Dilatar as Narinas Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_dilatar_narinas_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Dilatar as Narinas Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_dilatar_narinas_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Dilatar as Narinas Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevador_labio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevador do Lábio Superior e Zigomático Menor Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevador_labio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevador do Lábio Superior e Zigomático Menor Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevador_labio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevador do Lábio Superior e Zigomático Menor Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevador_labio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevador do Lábio Superior e Zigomático Menor Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevador_labio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevador do Lábio Superior e Zigomático Menor Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevador_labio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevador do Lábio Superior e Zigomático Menor Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_canto_labio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevar o Canto do Lábio Superior Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_canto_labio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Canto do Lábio Superior Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_canto_labio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Canto do Lábio Superior Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_canto_labio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Canto do Lábio Superior Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_canto_labio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevar o Canto do Lábio Superior Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_canto_labio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Canto do Lábio Superior Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_labio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevar o Lábio Superior Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_labio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Lábio Superior Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_labio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Lábio Superior Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_labio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Lábio Superior Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_labio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Elevar o Lábio Superior Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_elevar_labio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Elevar o Lábio Superior Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_enrugar_mento_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Enrugar o Mento Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_enrugar_mento_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Enrugar o Mento Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_enrugar_mento_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Enrugar o Mento Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_enrugar_mento_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Enrugar o Mento Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_enrugar_mento_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Enrugar o Mento Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_enrugar_mento_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Enrugar o Mento Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_frontal_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Frontal Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_frontal_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Frontal Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_frontal_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Frontal Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_frontal_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Frontal Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_frontal_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Frontal Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_frontal_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Frontal Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_bochecha_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Aproximar os Lábios e Comprimir as Bochechas Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_bochecha_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Lábios e Comprimir as Bochechas Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_bochecha_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Lábios e Comprimir as Bochechas Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_bochecha_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Lábios e Comprimir as Bochechas Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_bochecha_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Aproximar os Lábios e Comprimir as Bochechas Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_bochecha_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Lábios e Comprimir as Bochechas Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_fechado_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Lábios Fechados, Levar Canto da Boca P/ Lateral Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_fechado_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Lábios Fechados, Levar Canto da Boca P/ Lateral Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_fechado_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Lábios Fechados, Levar Canto da Boca P/ Lateral Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_fechado_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Lábios Fechados, Levar Canto da Boca P/ Lateral Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_fechado_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Lábios Fechados, Levar Canto da Boca P/ Lateral Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_labio_fechado_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Lábios Fechados, Levar Canto da Boca P/ Lateral Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_mento_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Quadrado do Mento Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_mento_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Quadrado do Mento Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_mento_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Quadrado do Mento Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_mento_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Quadrado do Mento Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_mento_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Quadrado do Mento Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_mento_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Quadrado do Mento Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculares_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porções Musculares Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculares_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porções Musculares Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculares_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porções Musculares Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculares_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porções Musculares Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculares_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porções Musculares Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculares_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porções Musculares Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculos_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Músculos Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculos_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Músculos Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculos_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Músculos Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculos_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Músculos Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculos_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Músculos Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_musculos_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Músculos Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_nariz_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Franzir o Nariz Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_nariz_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir o Nariz Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_nariz_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir o Nariz Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_nariz_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir o Nariz Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_nariz_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Franzir o Nariz Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_nariz_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir o Nariz Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_devagar_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Fechar os Olhos Devagar Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_devagar_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos Devagar Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_devagar_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos Devagar Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_devagar_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos Devagar Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_devagar_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Fechar os Olhos Devagar Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_devagar_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos Devagar Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_forca_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Fechar os Olhos com Força Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_forca_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos com Força Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_forca_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos com Força Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_forca_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos com Força Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_forca_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Fechar os Olhos com Força Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_olhos_forca_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Fechar os Olhos com Força Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbicular_labio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Obicular do Lábio Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbicular_labio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Obicular do Lábio Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbicular_labio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Obicular do Lábio Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbicular_labio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Obicular do Lábio Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbicular_labio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Obicular do Lábio Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbicular_labio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Obicular do Lábio Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbitaria_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Orbitária Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbitaria_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Orbitária Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbitaria_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Orbitária Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbitaria_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Orbitária Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbitaria_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Orbitária Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_orbitaria_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Orbitária Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_palpebral_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Palpebral Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_palpebral_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Palpebral Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_palpebral_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Palpebral Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_palpebral_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Palpebral Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_palpebral_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Palpebral Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_palpebral_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Palpebral Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_pescoco_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Contrair Pescoço Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_pescoco_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Contrair Pescoço Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_pescoco_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Contrair Pescoço Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_pescoco_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Contrair Pescoço Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_pescoco_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Contrair Pescoço Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_pescoco_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Contrair Pescoço Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_piramidal_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Piramidal Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_piramidal_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Piramidal Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_piramidal_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Piramidal Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_piramidal_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Piramidal Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_piramidal_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Piramidal Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_piramidal_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Piramidal Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_platisma_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Platisma Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_platisma_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Platisma Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_platisma_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Platisma Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_platisma_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Platisma Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_platisma_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Platisma Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_platisma_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Platisma Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_risorio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Risório Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_risorio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Risório Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_risorio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Risório Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_risorio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Risório Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_risorio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Risório Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_risorio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Risório Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_superciliar_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Superciliar Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_superciliar_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Superciliar Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_superciliar_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Superciliar Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_superciliar_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Superciliar Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_superciliar_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Superciliar Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_superciliar_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Superciliar Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_supercilios_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Aproximar os Supercílios Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_supercilios_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Supercílios Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_supercilios_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Supercílios Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_supercilios_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Supercílios Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_supercilios_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Aproximar os Supercílios Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_supercilios_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Aproximar os Supercílios Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_testa_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Franzir a Testa Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_testa_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir a Testa Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_testa_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir a Testa Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_testa_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir a Testa Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_testa_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Franzir a Testa Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_testa_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Franzir a Testa Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_transversal_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Transversal Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_transversal_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Transversal Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_transversal_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Transversal Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_transversal_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Transversal Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_transversal_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Porção Transversal Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_transversal_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Porção Transversal Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_triangular_labio_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Triangular do Lábio Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_triangular_labio_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Triangular do Lábio Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_triangular_labio_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Triangular do Lábio Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_triangular_labio_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Triangular do Lábio Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_triangular_labio_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Triangular do Lábio Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_triangular_labio_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Triangular do Lábio Esq. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_zigomatico_dir_S',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Zigomático Dir. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_zigomatico_dir_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Zigomático Dir. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_zigomatico_dir_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Zigomático Dir. [T]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_zigomatico_esq_c',
            field=models.CharField(blank=True, choices=[('[0] - Zero', '[0] - Zero'), ('[1] - Regular', '[1] - Regular'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Zigomático Esq. [C]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_zigomatico_esq_s',
            field=models.CharField(blank=True, choices=[('[0] - Ausência', '[0] - Ausência'), ('[1] - Inibição Voluntária', '[1] - Inibição Voluntária'), ('[2] - Inibição Por Pressão Digital', '[2] - Inibição Por Pressão Digital')], max_length=40, verbose_name='Zigomático Esq. [S]'),
        ),
        migrations.AddField(
            model_name='fisioterapiaparalisiafacial',
            name='prova_zigomatico_esq_t',
            field=models.CharField(blank=True, choices=[('[0] - Atonia', '[0] - Atonia'), ('[1] - Diminuído ou Aumentado', '[1] - Diminuído ou Aumentado'), ('[2] - Normal', '[2] - Normal')], max_length=40, verbose_name='Zigomático Esq. [T]'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_auditiva',
            field=models.CharField(blank=True, choices=[('Hipoacusia', 'Hipoacusia'), ('Hiperacusia', 'Hiperacusia'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Alteração Auditiva'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_conjuntivite',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Conjuntivite'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_desvio_facial',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Desvio Facial'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_desvio_septo',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Desvio do Septo Nasal'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_dor',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Dor Retroauricular'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_gustativa',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Alteração Gustativa'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_lagoftalmo',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Lagoftalmo'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_lingua',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Motricidade da Língua'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_linguagem',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Alterações da Linguagem (P-B-M)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_paralisia',
            field=models.CharField(blank=True, choices=[('Central', 'Central'), ('Periférica', 'Periférica')], max_length=40, verbose_name='Paralisia Facial Difinitiva'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_reflexo_ciliar',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Retardado', 'Retardado')], max_length=40, verbose_name='Reflexo Ciliar'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_sinal_bell',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sinal Bell'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_sinal_negro',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sinal Negro'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_sincinesias',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sincinésias'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_sulco_face',
            field=models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=40, verbose_name='Sulcos da Face'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='exame_tonus',
            field=models.CharField(blank=True, choices=[('Hipertônico', 'Hipertônico'), ('Hipotônico', 'Hipotônico'), ('Normal', 'Normal')], max_length=40, verbose_name='Tônus Muscular'),
        ),
    ]
