# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0058_auto_20171128_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioterapiaOrtopediaReavaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data')),
                ('estagiario', models.CharField(blank=True, max_length=40, verbose_name='Estagiário (a)')),
                ('movimento_ativo_1', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [1]')),
                ('movimento_ativo_1_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [1]')),
                ('movimento_ativo_1_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [1]')),
                ('movimento_ativo_2', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [2]')),
                ('movimento_ativo_2_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [2]')),
                ('movimento_ativo_2_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [2]')),
                ('movimento_ativo_3', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [3]')),
                ('movimento_ativo_3_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [3]')),
                ('movimento_ativo_3_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [3]')),
                ('movimento_ativo_4', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [4]')),
                ('movimento_ativo_4_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [4]')),
                ('movimento_ativo_4_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [4]')),
                ('movimento_passivo_1', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [1]')),
                ('movimento_passivo_1_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [1]')),
                ('movimento_passivo_1_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [1]')),
                ('movimento_passivo_2', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [2]')),
                ('movimento_passivo_2_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [2]')),
                ('movimento_passivo_2_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [2]')),
                ('movimento_passivo_3', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [3]')),
                ('movimento_passivo_3_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [3]')),
                ('movimento_passivo_3_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [3]')),
                ('movimento_passivo_4', models.CharField(blank=True, max_length=40, verbose_name='Movimento Realizado [4]')),
                ('movimento_passivo_4_eva', models.CharField(blank=True, choices=[('Dor Durante o Movimento', 'Dor Durante o Movimento'), ('Dor no Final do Movimento', 'Dor no Final do Movimento')], max_length=40, verbose_name='EVA [4]')),
                ('movimento_passivo_4_amplitude', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduzida', 'Reduzida')], max_length=40, verbose_name='Amplitude [4]')),
                ('teste_repeticao_1', models.TextField(blank=True, verbose_name='Movimento ou postura realizados')),
                ('teste_repeticao_2', models.TextField(blank=True, verbose_name='O que ocorreu com a dor durante o movimento? (Produz, abole, aumenta, diminui, nenhum efeito.)')),
                ('teste_repeticao_3', models.TextField(blank=True, verbose_name='O que ocorreu com a dor após o movimento? (Melhor, pior, não melhor, não pior, nenhum efeito)')),
                ('teste_repeticao_4', models.TextField(blank=True, verbose_name='O que ocorreu com a amplitude de movimento? (Aumento, diminuiu, nenhum efeito.)')),
                ('diagnostico_fisioterapeutico', models.TextField(blank=True, verbose_name='Diagnóstico Fisioterapeutico')),
                ('objetivo_dor', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Abolir a Dor')),
                ('objetivo_tonus', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Normalizar Tônus')),
                ('objetivo_propriocepcao', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Normalizar Propriocepção')),
                ('objetivo_marcha', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Normalizar Marcha')),
                ('objetivo_adm', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name="Normalizar Adm's")),
                ('objetivo_sensibilidade', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Estimular Sensibilidade')),
                ('objetivo_inflamacao', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Abolir Inflamação')),
                ('objetivo_aderencia', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Liberar Aderências')),
                ('objetivo_fortalecer_musculatura', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Fortalecer Musculatura')),
                ('objetivo_trofismo', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Normalizar Trofismo')),
                ('objetivo_alongar_musculatura', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Alongar Musculatura')),
                ('objetivo_edema', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Abolir Edema')),
                ('objetivo_avd', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name="Normalizar Avd's")),
                ('objetivo_postura', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Corrigir Postura')),
                ('proposta_crioterapia', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Crioterapia')),
                ('proposta_ultra_som', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Ultra Som')),
                ('proposta_microondas', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Microondas')),
                ('proposta_ondas_curtas', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Ondas Curtas')),
                ('proposta_infravermelho', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Infravermelho')),
                ('proposta_laser', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Laser')),
                ('proposta_tens', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='T.E.N.S.')),
                ('proposta_interferencial', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Interferencial')),
                ('proposta_fes', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='FES')),
                ('proposta_russa', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Russa')),
                ('proposta_diadinamica', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Diadinâmica')),
                ('proposta_turbilhao', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Turbilhão')),
                ('proposta_contraste', models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=40, verbose_name='Contraste')),
                ('proposta_outras', models.TextField(blank=True, verbose_name='Outros')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Ficha de Reavaliação',
                'ordering': ['data'],
                'verbose_name_plural': 'Fichas de Reavaliação',
            },
        ),
    ]
