# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0061_auto_20171128_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisioterapiaortopediaavaliacao',
            name='atendimento_medico',
        ),
        migrations.AddField(
            model_name='fisioterapiaortopediaavaliacao',
            name='atendimento_estagiario',
            field=models.CharField(blank=True, max_length=40, verbose_name='Estagiário (a)'),
        ),
    ]
