# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0062_auto_20171128_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fisioterapiaortopediaavaliacao',
            old_name='proprocepcao',
            new_name='propriocepcao',
        ),
    ]
