# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0063_auto_20171128_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaortopediaavaliacao',
            name='ombro_dir_80',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ombro Dir. Rotação Externa 80°'),
        ),
    ]
