# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20180324_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Nome da Disciplina'),
        ),
    ]
