# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20170811_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['descricao'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
