# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20170811_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, unique=True, verbose_name='Nome da Disciplina')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Setor', verbose_name='Curso')),
            ],
            options={
                'verbose_name_plural': 'Setores',
                'verbose_name': 'Setor',
                'ordering': ['descricao'],
            },
        ),
    ]
