# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_disciplina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['setor', 'descricao'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
    ]
