# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_auto_20170901_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, unique=True, verbose_name='Área de Atendimento')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Setor', verbose_name='Setor')),
            ],
            options={
                'ordering': ['setor', 'descricao'],
                'verbose_name': 'Área de Atendimento',
                'verbose_name_plural': 'Áreas de Atendimento',
            },
        ),
    ]
