# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_areaatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome'),
        ),
    ]
