# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='colaborador',
            field=models.CharField(choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=10, verbose_name='Colaborador da instituição?'),
        ),
    ]
