# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20180223_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='estagiario',
            field=models.CharField(blank=True, max_length=30, verbose_name='Estagiário'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='supervisor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Supervisor'),
        ),
    ]
