# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180223_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='atendimento_supervisor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaesclerosemultipla',
            name='atendimento_supervisor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologica',
            name='atendimento_supervisor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaortopediaavaliacao',
            name='atendimento_supervisor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='atendimento_supervisor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparkinson',
            name='atendimento_supervisor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiatrm',
            name='atendimento_supervisor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supervisor (a)'),
        ),
    ]
