# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20180223_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaavaliacaofeminina',
            name='data',
            field=models.DateField(verbose_name='Data da Avaliação'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaavaliacaofeminina',
            name='data_atendimento',
            field=models.DateField(verbose_name='Data do Atendimento'),
        ),
    ]
