# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20180226_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='patologias_alergias',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=3, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='patologias_articular',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=3, verbose_name='Comprometimento Articular'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='patologias_cardiopatias',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=3, verbose_name='Cardiopatias'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='patologias_diabetes',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=3, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='patologias_dor',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=3, verbose_name='Dor'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='patologias_hipertensao',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=3, verbose_name='Hipertensão Arterial'),
        ),
    ]
