# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20180226_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaavaliacaogestacional',
            name='gestacional_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data dos Primeiros Movimentos Fetais'),
        ),
    ]
