# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20180614_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaortopediaavaliacao',
            name='anamnese_data_inicio',
            field=models.DateField(blank=True, max_length=40, null=True, verbose_name='Data do Início'),
        ),
    ]
