# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20180614_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='atendimento_estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaesclerosemultipla',
            name='atendimento_estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='estagiario',
            field=models.CharField(max_length=30, verbose_name='Estagiário'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologica',
            name='atendimento_estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaortopediaavaliacao',
            name='atendimento_estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaortopediareavaliacao',
            name='estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='atendimento_estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparkinson',
            name='atendimento_estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiatrm',
            name='atendimento_estagiario',
            field=models.CharField(max_length=40, verbose_name='Estagiário (a)'),
        ),
    ]
