# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_auto_20180626_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='avaliador',
            field=models.CharField(max_length=20, verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaberg',
            name='local',
            field=models.CharField(max_length=20, verbose_name='Local'),
        ),
    ]
