# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20180627_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapiaacidentevascularencefalico',
            name='atendimento_supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaesclerosemultipla',
            name='atendimento_supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiageriatriaavalicao',
            name='supervisor',
            field=models.CharField(max_length=30, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='fisioterapianeurologica',
            name='atendimento_supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaortopediaavaliacao',
            name='atendimento_supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparalisiafacial',
            name='atendimento_supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiaparkinson',
            name='atendimento_supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor (a)'),
        ),
        migrations.AlterField(
            model_name='fisioterapiatrm',
            name='atendimento_supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor (a)'),
        ),
    ]
