# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.CharField(max_length=30, verbose_name='Nome da Disciplina'),
        ),
    ]
